{{- if .Values.additionalconf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blocking-rules.cmname" . }}
  labels:
    {{- include "blocking-rules.labels" . | nindent 4 }}
    {{- if .Values.additionalconf.labels }}
      {{- toYaml .Values.additionalconf.labels | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: {{ .Release.Name }}
  {{- if .Values.additionalconf.annotations }} 
  annotations:
    {{- toYaml .Values.additionalconf.annotations | nindent 4 }}
  {{- end }}     
data:
  {{- if .Values.additionalconf.config }}
  additional.conf: |-
    {{- toYaml .Values.additionalconf.config | nindent 6 }}
  {{- else }}
  additional.conf: |- 
    server {
        listen       8080;
        listen  [::]:8080;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        error_page 400 401 402 403 404 500 501 502 503 504              /index.html;
    }
  {{- end }}
{{- end }}
